### PR TITLE
Updating to `embedded-hal` v1.0

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR refactors the driver to use the 1.0 release of the `embedded-hal`.

Because of `embedded-hal-bus` being available to provide for SPI buses with multiple peripherals, the `Ref` implementations have been removed entirely because this crate doesn't need to worry about sharing the SPI bus across multiple owners any longer.

### CODE REVIEW

**Comment by kellerkindt** [comment]
LGTM except the removal of the `*Ref` part. Maybe I dont understand it or overlook something. Consider the following example (semi-pseudo-code):

```rust
pub struct MyControllerState {
    spi: SpiBus<...>,
    cs_w5500: OutputPin<..>,
    cs_ds93c46: OutputPin<...>,
    w5500_state: InactiveDevice<w5500::Manual>,
    ds93c46_state: DS93C46<..>,
}

impl MyControllerState {
    pub fn new(...) -> Self { ... }

    pub fn send_udp(&mut self, destination: SocketAddr, data: &[u8]) -> Result<...> {
         let mut device = self.w5500_state.activate_ref(FourWireRef::new(&mut self.spi, &mut self.cs_w5500))?;
         let mut socket = device.socket().unwrap(); // for simplicity of this example, this socket is not cached in MyControllerState
         device.connect(&mut socket, destination).unwrap(); // for simplicity of this example...
         nb::block!(device.send(socket, data))
    }


    pub fn write_eeprom(&mut self, position: usize, data: &[u8], delay: impl DelayMs<u16>) -> Result<...> {
        self.ds93c46_state.enable_write(spi, delay)?;
        let result = self.ds93c46_state.write(spi, delay, position, data);
        self.ds93c46_state.disable_write(spi, delay)?;
        result
    }
}
```

In this example, the SPI bus is shared between the w5500 chip and an eeprom:
  - without additional runtime cost
  - and with a compile-time-check that prevents me from actually borrowing/accessing it twice.

How would that look with the `embedded-hal-bus` crate?

**Comment by ryan-summers** [comment]
That would look (roughly) like:
```rs
// Instantiate the SPI peripheral
let bus =hal::spi::new();

let bus_refcell = core::cell::RefCell::new(bus);
let w5500_spi = embedded_hal_bus::spi::RefCellDevice::new(&bus_refcell, w5500_csn);
let w5500 = w5500::UninitializedDevice::new(w5500::bus::FourWire(w5500_spi)).initialize().unwrap();

let eeprom_spi = embedded_hal_bus::spi::RefCellDevice::new(&bus_refcell, eeprom_csn);
let eeprom = Eeprom::new(eeprom_spi)
```

You can use different types of storage for the actual bus depending on your application requirements (i.e. Mutex-based, Atomic-access based if you're using RTIC, or a critical-section protected bus). https://docs.rs/embedded-hal-bus/latest/embedded_hal_bus/spi/index.html has all of the supported bus synchronization types currently

**Comment by ryan-summers** [comment]
Also, I want to point out that the `embedded-hal-bus` approach is likely less runtime cost than you currently have. As it stands, you're moving the `spi` peripheral around between your drivers, which is copying around data and updating internal state. The approach of `embedded-hal-bus` requires generally either:
1. No runtime overhead at all (i.e. `RefCellDevice`)
2. Single atomic flip runtime check (i.e. `AtomicDevice`)
    * This would require using the NVIC to handle synchronization across multiple ISR contents, like what RTIC does
4. Critical section (interrupt disable/enable) (i.e. `CriticalSectionDevice`)

**Comment by ryan-summers** [comment]
I'd also be happy to reinstate `InactiveDevice` to accomodate the existing use case you have. I don't think the Ref devices make sense given that the `embedded-hal-bus` essentially does that for you via the `RefCell` types

**Comment by kellerkindt** [comment]
> I'd also be happy to reinstate `InactiveDevice` to accomodate the existing use case you have. I don't think the Ref devices make sense given that the `embedded-hal-bus` essentially does that for you via the `RefCell` types

Sorry, I am currently at work and cannot look into this in detail until later. I support the idea to keep at least `InactiveDevice` around. I just noted that the trait `SpiDevice` is implemented on [`&mut "impl SpiDevice"`](https://docs.rs/embedded-hal/1.0.0/embedded_hal/spi/trait.SpiDevice.html#impl-SpiDevice%3CWord%3E-for-%26mut+T), with the `InactiveDevice` this would then support my example from above again.

**Comment by ryan-summers** [comment]
No worries, I've reintroduced the `InactiveDevice` and associated functions

**Comment by kellerkindt** [comment]
Sorry, I should have been more verbose with my response. There is still the need for the `DeviceRefMut` but without our custom `BusRef` impl anymore, so that the call `w5500_state.activate_ref` is possible. I suggest to restore most of the removed lines in `src/device.rs`.

Regarding your earlier points

> As it stands, you're moving the `spi` peripheral around between your drivers, which is copying around data and updating internal state.

This isn't true, because only references are passed around. The `DeviceRefMut` is nothing more than two references: one to the current driver state, one to the spi-bus. Nothing needs to be copied around.

If you have the spare time, it might be useful to add one or two sentences to the `DeviceRefMut` and/or `InactiveDevice` for that. Maybe even referencing [`&mut "impl SpiDevice"`](https://docs.rs/embedded-hal/1.0.0/embedded_hal/spi/trait.SpiDevice.html#impl-SpiDevice%3CWord%3E-for-%26mut+T) / [`&mut "impl SpiBus"`](https://docs.rs/embedded-hal/1.0.0/embedded_hal/spi/trait.SpiBus.html#impl-SpiBus%3CWord%3E-for-%26mut+T).

Sorry to bother you so much with this and thank you.

**Comment by ryan-summers** [comment]
@kellerkindt I proposed a new approach to provide an equivalent of `DeviceRefMut` without any of the code duplication. Let me know what you think. It changes the `Device` type signature to add one more trait indirection, but this is a simple transformation for users:
`Device<BUS, Mode>` -> `Device<BUS, DeviceState<Mode>>`

**Comment by ryan-summers** [comment]
Thanks for the discussion and review! :)

**Pull request merged**
