### PR TITLE
Removed all trait objects and replaced with bound generics

### PR DESCRIPTION
**Pull request by jonahbron**
Using trait objects broke the linking process when compiling to AVR.  This PR replaces them all with bound generics instead.  It does not alter the interface of the library.

### CODE REVIEW

**Comment by kellerkindt** [comment]
I really do not understand why this would fix your issue, but if it helps, I am okay with it.

**Comment by jonahbron** [comment]
@kellerkindt apparently trait objects require a u64 identifier, which does not work on 8-bit AVR.  See this comment:

https://github.com/avr-rust/rust/issues/149#issuecomment-512706754

**Comment by kellerkindt** [comment]
(might refactor it a bit before releasing a new version, but before that, I am on vacation)
In case you @jonahbron didn't already know: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies

**Comment by kellerkindt** [comment]
(might refactor it a bit before releasing a new version, but before that, I am on vacation)
In case you @jonahbron didn't already know: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies

**Comment by jonahbron** [comment]
Cool, thank you @kellerkindt

**Pull request merged**
