### PR TITLE
Renaming trait function names, cleaning up docs

### LINKED ISSUE #36: Rust may complain when using `embedded-nal` trait objects directly
When following the example on the README, there's an issue with the TCP example.

Specifically, the compiler will complain about the `connect()` function being private. This arises because the `TcpSocket` exposes two `connect()` functions - one as a private function, and one as a public trait method of `TcpClientStack`.

[Rust's method call ordering](https://doc.rust-lang.org/reference/expressions/method-call-expr.html) specifies that the private function is found first, which results in the compiler thinking that incorrect arguments and invalid private scope is identified. 

Users can work around this by explicitly casting the socket to a trait object (See https://doc.rust-lang.org/reference/expressions/call-expr.html#disambiguating-function-calls), but this is incredibly not user-friendly.

We should rename all of the private methods of the sockets to not conflict with the trait implementations to avoid this confusion.

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR fixes #36 by renaming some of the internal function names. It also cleans up the docs so that they get run automatically by `cargo test`

### CODE REVIEW

**Comment by kellerkindt** [comment]
I'd like to keep the example with `.activate_ref` and I don't like the underscore-prefix at all. Is there another naming alternative? `internal_connect` does not really look that much better... Either way, I am in favor of renaming internal method names if it improves the user experience.

**Comment by ryan-summers** [comment]
> I'd like to keep the example with .activate_ref and I don't like the underscore-prefix at all. Is there another naming alternative? internal_connect does not really look that much better... Either way, I am in favor of renaming internal method names if it improves the user experience.

Both of these are valid points that I thought about when make the PR, but I got lazy. Thanks for pointing them out, I'll clean them up

**Comment by ryan-summers** [comment]
Alright, now properly fixed. I also realized that the doc string include wasn't included as I wanted. Now the README is pulled into the crate-level docs when published to crates.io:

**Review by kellerkindt — APPROVED** [review]
LGTM

**Comment by kellerkindt** [comment]
Thanks!

**Pull request merged**
